### ISSUE TITLE
V11:  Active Effect Deprecations

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#282]
Not breaking obviously, but want to clean up given the amount they spam the warning

```
commons.js:2004 Error: You are accessing ActiveEffect._getSourceName which is deprecated.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:1993:19)
    at ActiveEffect4e._getSourceName (foundry.js:18076:19)
    at ActiveEffect4e.prepareActiveEffectCategories (effects.js:223:6)
    at ActorSheet4eNPC.getData (actor-sheet.js:165:33)
    at ActorSheet4eNPC._render (foundry.js:5726:29)
    at ActorSheet4eNPC._render (foundry.js:6444:17)
    at ActorSheet4eNPC.render (foundry.js:5683:10)
    at ActorSheet4eNPC.render (foundry.js:7023:18)
    at Token._onClickLeft2 (foundry.js:55352:17)
    at MouseInteractionManager.callback (foundry.js:31043:17)
    at #handleClickLeft2 (foundry.js:31247:15)
    at #handleMouseDown (foundry.js:31214:83)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerDown (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerDown (earcut.js:128:75)
```

```
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:1993:19)
    at ActiveEffect4e._logDataFieldMigration (commons.js:8403:14)
    at ActiveEffect4e.get (commons.js:8892:28)
    at lookupProperty (handlebars.min.js:27:16153)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:15:91)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Object.<anonymous> (handlebars.min.js:27:7289)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:23:49)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7554
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7522
    at Object.<anonymous> (handlebars.min.js:27:7597)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:13:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:275:28)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7637:10)
    at async ActorSheet4eNPC._renderInner (foundry.js:5887:16)
    at async ActorSheet4eNPC._renderInner (foundry.js:6455:18)
    at async ActorSheet4eNPC._render (foundry.js:5732:19)
    at async ActorSheet4eNPC._render (foundry.js:6444:5)
```

```
commons.js:2004 Error: You are accessing ActiveEffect4e#label which has been migrated to ActiveEffect4e#name
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:1993:19)
    at ActiveEffect4e._logDataFieldMigration (commons.js:8403:14)
    at ActiveEffect4e.get (commons.js:8892:28)
    at lookupProperty (handlebars.min.js:27:16153)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:15:91)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Object.<anonymous> (handlebars.min.js:27:7289)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:23:49)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7554
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7522
    at Object.<anonymous> (handlebars.min.js:27:7597)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:13:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:275:28)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7637:10)
    at async ActorSheet4eNPC._renderInner (foundry.js:5887:16)
    at async ActorSheet4eNPC._renderInner (foundry.js:6455:18)
    at async ActorSheet4eNPC._render (foundry.js:5732:19)
    at async ActorSheet4eNPC._render (foundry.js:6444:5)
```

**Comment by draconas1** [comment]
I think we've got all the ones I've spotted in my game.  Can always work on more as they appear.
